apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: oldledger/ticketing-client
          # resources:
          #   limits:
          #     memory: "512Mi"
          #     cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
  labels:
    app: client
    service: client-srv
spec:
  selector:
    app: client
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
